import type { Metadata } from "next";
import { Geist, Geist_Mono, VT323, Pixelify_Sans } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const vt323 = VT323({
  variable: "--font-vt323",
  subsets: ["latin"],
  weight: "400",
});

const pixelfySans = Pixelify_Sans({
  variable: "--font-pixelify_sans",
  subsets: ["latin"],
  weight: "400",
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${vt323.variable} ${pixelfySans.variable} antialiased`}
      >
        <div className="bg-[#F2E4CC] min-h-screen [font-family:var(--font-pixelify_sans)]">
          {children}
        </div>
      </body>
    </html>
  );
}
